@startuml
!include style.puml

start

:user enters 'add-attendance c\1 l\1 s\1' in
the command box;

:AddAttendanceCommandParser parses the argument;

if () then ([valid command input format])
    if () then ([valid indexes])
        :get targetStudent and targetModuleClass
        from the respective filtered lists;
        :create a new ModuleClass
        object with attendance added;
        :update targetModuleClass with
         new moduleClass in the model;
        :commit this state to the model;
    else ([else])
        :throws CommandException
        with error message;
    endif
else ([else])
    :throws ParseException
    with command usage
    direction;
endif
:returns feedback to user;

stop

@enduml