@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor black
skinparam classBackgroundColor LOGIC_COLOR_T1
skinparam fontColor black

box Attendance Retrieval LOGIC_COLOR_T1
participant ":<<Class>>\nModuleClassUtil" as ModuleClassUtil LOGIC_COLOR
participant ":ModuleClass" as ModuleClass LOGIC_COLOR
participant ":<<Class>>\nLessonUtil" as LessonUtil LOGIC_COLOR
participant ":Lesson" as Lesson LOGIC_COLOR
participant ":<<Class>>\nAttendanceRecordListUtil" as AttendanceRecordListUtil LOGIC_COLOR
participant ":AttendanceRecordList" as AttendanceRecordList LOGIC_COLOR
participant ":AttendanceRecord" as AttendanceRecord LOGIC_COLOR
participant ":Attendance" as Attendance LOGIC_COLOR
end box

[-> ModuleClassUtil : getAttendanceFrom\nModuleClass

ModuleClassUtil -> ModuleClass :getLessons
ModuleClassUtil -> LessonUtil :getAttendanceFromLesson

LessonUtil -> Lesson :getAttendance\nRecordList
LessonUtil -> AttendanceRecordListUtil :getAttendanceFrom\nAttendanceRecordList

AttendanceRecordListUtil -> AttendanceRecordList :getAttendanceRecord
AttendanceRecordListUtil -> AttendanceRecord :getAttendance

AttendanceRecord -> Attendance :get

@enduml
