@startuml

!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassFontColor<<Transparent>> #FFFFFF
skinparam ClassBorderColor<<Transparent>> #FFFFFF
skinparam ClassBackgroundColor<<Transparent>> #FFFFFF

title No Next Command Available

class Hidden1
class Hidden2

class Cache1 as "Cache: [Cached value]"
class Cache2 as "Cache: [Cached value]"


package "History (Before)" <<Rectangle>>{
    class State1 as "  __command0:String__  "
    class State2 as "  __command1:String__  "
    class State3 as "  __command2:String__  " <<Transparent>>
}

note "The cached value\nis returned" as N1

package "History (After)" <<Rectangle>>{
    class State4 as "  __command0:String__  "
    class State5 as "  __command1:String__  "
    class State6 as "  __command2:String__  " <<Transparent>>
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
State4 -[hidden]right-> State5
State5 -[hidden]right-> State6
Hidden1 -[hidden]down- "History (Before)"
Hidden2 -[hidden]down- "History (After)"
Hidden1 -[hidden]right-> Cache1
Hidden2 -[hidden]right-> Cache2
hide Hidden1
hide Hidden2

class Pointer as "  Pointer  " #FFFFFF
class Pointer2 as "  Pointer  " #FFFFFF
Pointer -up-> State2
Pointer2 -up-> State6



@enduml
