@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Model (Overview)" <<Rectangle>>{
Interface ReadOnlyTutorsPet <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class TutorsPet
Class VersionedTutorsPet
Class ReadOnlyTutorsPet
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class TutorsPetState

Package Student {
Class Student
Class UniqueStudentList
}

Package ModuleClass {
Class ModuleClass
Class UniqueModuleClassList
}

Package Lesson {
Class Lesson
}

Package Attendance {
}

Package Components {
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

VersionedTutorsPet *--right--> "*" TutorsPetState : "    "
TutorsPetState -down-> ReadOnlyTutorsPet
VersionedTutorsPet --|> TutorsPet
TutorsPet .left.|> ReadOnlyTutorsPet : "    "

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o-right-> "1" VersionedTutorsPet : "                     "
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

TutorsPet *---> "1" UniqueStudentList
UniqueStudentList o--> "*" Student
Student *--> Components

TutorsPet *---> "1" UniqueModuleClassList
UniqueModuleClassList o--> "*" ModuleClass
ModuleClass ..right.> Student
ModuleClass *--> Components
ModuleClass *-right-> Lesson

Lesson *-down-> Attendance

Attendance -[hidden]left-> Components

ModelManager --> Student : filtered\nstudent list
ModelManager --> ModuleClass : filtered\nclass list

@enduml
