@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TutorsPetParser" as TutorsPetParser LOGIC_COLOR
participant ":StatisticsCommandParser" as StatisticsCommandParser LOGIC_COLOR
participant "d:StatisticsCommand" as StatisticsCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant "<<Class>>\nModuleClassUtil" as ModuleClassUtil LOGIC_COLOR
participant "<<Class>>\nLessonUtil" as LessonUtil LOGIC_COLOR

end box

[-> LogicManager : execute("stats c\1 s\1")
activate LogicManager

LogicManager -> TutorsPetParser : parseCommand("stats c\1 s\1")
activate TutorsPetParser

create StatisticsCommandParser
TutorsPetParser -> StatisticsCommandParser
activate StatisticsCommandParser

StatisticsCommandParser --> TutorsPetParser
deactivate StatisticsCommandParser

TutorsPetParser -> StatisticsCommandParser: parse("c\1 s\1")
activate StatisticsCommandParser

create StatisticsCommand
StatisticsCommandParser -> StatisticsCommand
activate StatisticsCommand

StatisticsCommand --> StatisticsCommandParser : s
deactivate StatisticsCommand

StatisticsCommandParser --> TutorsPetParser : s
deactivate StatisticsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
StatisticsCommandParser -[hidden]-> TutorsPetParser
destroy StatisticsCommandParser

TutorsPetParser --> LogicManager : s
deactivate TutorsPetParser

LogicManager -> StatisticsCommand : execute()
activate StatisticsCommand

StatisticsCommand -> ModuleClassUtil : getAttendanceFromModuleClass(lesson, student)
activate ModuleClassUtil

loop hasLesson
    ModuleClassUtil -> LessonUtil : getAttendanceFromLesson(lesson, student)
    activate LessonUtil

    LessonUtil -> ModuleClassUtil : attendances
    deactivate LessonUtil
end

ModuleClassUtil --> StatisticsCommand
deactivate ModuleClassUtil

create CommandResult
StatisticsCommand -> CommandResult
activate CommandResult

CommandResult --> StatisticsCommand
deactivate CommandResult

StatisticsCommand --> LogicManager : result
deactivate StatisticsCommand

[<--LogicManager
deactivate LogicManager
@enduml