@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Package Storage <<Rectangle>> {
Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface TutorsPetStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTutorsPetStorage
Class JsonSerializableTutorsPet

Package JsonAdaptedStudent <<Rectangle>> {
Class JsonAdaptedStudent
Class JsonAdaptedTag
Class JsonAdaptedName
}

Class JsonAdaptedModuleClass

Package JsonAdaptedLesson <<Rectangle>> {
Class JsonAdaptedLesson
Class JsonAdaptedAttendanceRecordList
Class JsonAdaptedAttendanceRecord
Class JsonAdaptedStudentAttendance
Class JsonAdaptedAttendance
}

Class JsonAdaptedUuid

}

StorageManager .left.|> Storage
StorageManager *-right-> UserPrefsStorage
StorageManager *-down-> TutorsPetStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonTutorsPetStorage .left.|> TutorsPetStorage
JsonTutorsPetStorage .down.> JsonSerializableTutorsPet
JsonSerializableTutorsPet *-down->"*" JsonAdaptedStudent
JsonSerializableTutorsPet *-down->"*" JsonAdaptedModuleClass
JsonAdaptedStudent *-down->"1" JsonAdaptedName
JsonAdaptedStudent *-down->"*" JsonAdaptedTag
JsonAdaptedModuleClass *-down->"1" JsonAdaptedName
JsonAdaptedModuleClass *-down->"*" JsonAdaptedUuid
JsonAdaptedModuleClass *-right->"*" JsonAdaptedLesson
JsonAdaptedLesson *-down->"1" JsonAdaptedAttendanceRecordList
JsonAdaptedAttendanceRecordList *-down->"0..52" JsonAdaptedAttendanceRecord
JsonAdaptedAttendanceRecord *-down->"*" JsonAdaptedStudentAttendance
JsonAdaptedStudentAttendance *-down->"1" JsonAdaptedUuid
JsonAdaptedStudentAttendance *-down->"1" JsonAdaptedAttendance
@enduml
