@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface TutorsPetStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonTutorsPetStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> TutorsPetStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonTutorsPetStorage .left.|> TutorsPetStorage
JsonTutorsPetStorage .down.> JsonSerializableTutorsPetStorage
JsonSerializableTutorsPetStorage .right.> JsonSerializablePerson
JsonSerializablePerson .right.> JsonAdaptedTag
@enduml
