@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam ClassStereotypeFontColor #000000
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
show members
hide empty members

Class TutorsPetState {
    {field} commitMessage: String
}
Interface ReadOnlyTutorsPet <<interface>>
Class TutorsPet
Class VersionedTutorsPet {
    {field} statePointer: int
}

TutorsPetState -up-> "1" ReadOnlyTutorsPet
TutorsPet -right[hidden]- TutorsPetState
TutorsPet .up.|> ReadOnlyTutorsPet
VersionedTutorsPet -up-|> TutorsPet
VersionedTutorsPet *-up-> "*" TutorsPetState
@enduml
