@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":TutorsPetParser" as TutorsPetParser LOGIC_COLOR
participant "command:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTutorsPet" as VersionedTutorsPet MODEL_COLOR
end box

[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> TutorsPetParser : parseCommand(undo)
activate TutorsPetParser

create UndoCommand
TutorsPetParser -> UndoCommand
activate UndoCommand

UndoCommand --> TutorsPetParser
deactivate UndoCommand

TutorsPetParser --> LogicManager : command
deactivate TutorsPetParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undo()
activate Model

Model -> VersionedTutorsPet : undo()
activate VersionedTutorsPet

VersionedTutorsPet -> VersionedTutorsPet : resetData(ReadOnlyTutorsPet)
activate VersionedTutorsPet
VersionedTutorsPet --> VersionedTutorsPet
deactivate VersionedTutorsPet

VersionedTutorsPet --> Model
deactivate VersionedTutorsPet

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
